// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/playlists": {
            "post": {
                "description": "Creates a new playlist on the remote video hosting platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Creates a new playlist",
                "parameters": [
                    {
                        "description": "Required data to create a playlist",
                        "name": "meta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video_hosting.ItemMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Required metata are wrong in some ways"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/playlists/{id}": {
            "get": {
                "description": "Retrieve a playlist by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Get a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update a playlist by ID if it exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Update a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated playlist",
                        "name": "playlist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete the playlist by ID if it exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Delete a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/playlists/{pid}/videos/{vid}": {
            "put": {
                "description": "Add an existing playlist to an existing video",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Add a video to the selected playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "pid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "vid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Either the playlist or video don't exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/videos": {
            "post": {
                "description": "Upload a video from the object storage to the video hosting platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Upload a video",
                "parameters": [
                    {
                        "description": "Required data to upload a video",
                        "name": "videometa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/videos_controller.CreateVideoBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/videos/{id}": {
            "get": {
                "description": "Retrieve a video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Get a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update the video by ID if it exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Update a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated video",
                        "name": "video",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete the video by ID if it exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Delete a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/videos/{id}/thumbnail": {
            "post": {
                "description": "Set the thumbnail of an existing video on the remote video hosting platform",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Set the thumbnail of a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thumbnail content",
                        "name": "thumb",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "video_hosting.ItemMetadata": {
            "type": "object",
            "required": [
                "title",
                "visibility"
            ],
            "properties": {
                "description": {
                    "description": "Short text describing the content of the item\nYoutube actually limits to 5000 bytes, which *isn't* 5000 characters\nhttps://developers.google.com/youtube/v3/docs/videos#properties",
                    "type": "string",
                    "maxLength": 1000
                },
                "title": {
                    "description": "Title of the item\nThe max character limitation is currently taken from the Yt docs\nhttps://developers.google.com/youtube/v3/docs/videos#properties\nThis may change if another provider is requiring less than 100 characters",
                    "type": "string",
                    "maxLength": 100
                },
                "visibility": {
                    "description": "Visibility of the item",
                    "type": "string"
                }
            }
        },
        "video_hosting.Playlist": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Creation date",
                    "type": "string"
                },
                "description": {
                    "description": "Short description about what's in the playlist",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "itemCount": {
                    "description": "Number of video in this playlist",
                    "type": "integer"
                },
                "thumbnailUrl": {
                    "description": "Playlist thumbnail",
                    "type": "string"
                },
                "title": {
                    "description": "Playlist display name",
                    "type": "string"
                },
                "visibility": {
                    "description": "public/private/unlisted",
                    "type": "string"
                }
            }
        },
        "video_hosting.Video": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Creation date",
                    "type": "string"
                },
                "description": {
                    "description": "Video description",
                    "type": "string"
                },
                "duration": {
                    "description": "Video duration in seconds",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "description": "Playlist thumbnail",
                    "type": "string"
                },
                "title": {
                    "description": "Video display name",
                    "type": "string"
                },
                "visibility": {
                    "description": "public/private/unlisted",
                    "type": "string"
                }
            }
        },
        "videos_controller.CreateVideoBody": {
            "type": "object",
            "required": [
                "storageKey",
                "title",
                "visibility"
            ],
            "properties": {
                "description": {
                    "description": "Short text describing the content of the item\nYoutube actually limits to 5000 bytes, which *isn't* 5000 characters\nhttps://developers.google.com/youtube/v3/docs/videos#properties",
                    "type": "string",
                    "maxLength": 1000
                },
                "storageKey": {
                    "description": "Key to retrieve the video from the object storage",
                    "type": "string"
                },
                "title": {
                    "description": "Title of the item\nThe max character limitation is currently taken from the Yt docs\nhttps://developers.google.com/youtube/v3/docs/videos#properties\nThis may change if another provider is requiring less than 100 characters",
                    "type": "string",
                    "maxLength": 100
                },
                "visibility": {
                    "description": "Visibility of the item",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Video store",
	Description:      "An API to store and retrieve videos from a remote hosting service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
