// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/playlists": {
            "post": {
                "description": "Creates a new playlist on the remote video hosting platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Creates a new playlist",
                "parameters": [
                    {
                        "description": "Required data to create a playlist",
                        "name": "meta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video_hosting.ItemMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Required metata are wrong in some ways"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/playlists/{id}": {
            "get": {
                "description": "Retrieve a playlist by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Get a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update a playlist by ID if it exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "playlists"
                ],
                "summary": "Update a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Playlist"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete the playlist by ID if it exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Delete a playlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No playlist with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/videos": {
            "post": {
                "description": "Upload a video from the object storage to the video hosting platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Upload a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Required data to upload a video",
                        "name": "videometa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video_hosting.ItemMetadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/videos/{id}": {
            "get": {
                "description": "Retrieve a video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Get a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Update the video by ID if it exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Update a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video_hosting.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Delete the video by ID if it exists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Delete a video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "No video with this ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "video_hosting.ItemMetadata": {
            "type": "object",
            "required": [
                "description",
                "title",
                "visibility"
            ],
            "properties": {
                "description": {
                    "description": "Short text describing the content of the item",
                    "type": "string"
                },
                "title": {
                    "description": "Title of the item",
                    "type": "string"
                },
                "visibility": {
                    "description": "Visibility of the item",
                    "type": "string"
                }
            }
        },
        "video_hosting.Playlist": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Creation date",
                    "type": "string"
                },
                "description": {
                    "description": "Short description about what's in the playlist",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "itemCount": {
                    "description": "Number of video in this playlist",
                    "type": "integer"
                },
                "thumbnailUrl": {
                    "description": "Playlist thumbnail",
                    "type": "string"
                },
                "title": {
                    "description": "Playlist display name",
                    "type": "string"
                },
                "visibility": {
                    "description": "public/private/unlisted",
                    "type": "string"
                }
            }
        },
        "video_hosting.Video": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Creation date",
                    "type": "string"
                },
                "description": {
                    "description": "Video description",
                    "type": "string"
                },
                "duration": {
                    "description": "Video duration in seconds",
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "thumbnailUrl": {
                    "description": "Playlist thumbnail",
                    "type": "string"
                },
                "title": {
                    "description": "Video display name",
                    "type": "string"
                },
                "visibility": {
                    "description": "public/private/unlisted",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
