basePath: /
definitions:
  video_hosting.ItemMetadata:
    properties:
      description:
        description: |-
          Short text describing the content of the item
          Youtube actually limits to 5000 bytes, which *isn't* 5000 characters
          https://developers.google.com/youtube/v3/docs/videos#properties
        maxLength: 1000
        type: string
      title:
        description: |-
          Title of the item
          The max character limitation is currently taken from the Yt docs
          https://developers.google.com/youtube/v3/docs/videos#properties
          This may change if another provider is requiring less than 100 characters
        maxLength: 100
        type: string
      visibility:
        description: Visibility of the item
        type: string
    required:
    - title
    - visibility
    type: object
  video_hosting.Playlist:
    properties:
      createdAt:
        description: Creation date
        type: string
      description:
        description: Short description about what's in the playlist
        type: string
      id:
        type: string
      itemCount:
        description: Number of video in this playlist
        type: integer
      thumbnailUrl:
        description: Playlist thumbnail
        type: string
      title:
        description: Playlist display name
        type: string
      visibility:
        description: public/private/unlisted
        type: string
    type: object
  video_hosting.Video:
    properties:
      createdAt:
        description: Creation date
        type: string
      description:
        description: Video description
        type: string
      duration:
        description: Video duration in seconds
        type: integer
      id:
        type: string
      thumbnailUrl:
        description: Playlist thumbnail
        type: string
      title:
        description: Video display name
        type: string
      visibility:
        description: public/private/unlisted
        type: string
    type: object
  videos_controller.CreateVideoBody:
    properties:
      description:
        description: |-
          Short text describing the content of the item
          Youtube actually limits to 5000 bytes, which *isn't* 5000 characters
          https://developers.google.com/youtube/v3/docs/videos#properties
        maxLength: 1000
        type: string
      storageKey:
        description: Key to retrieve the video from the object storage
        type: string
      title:
        description: |-
          Title of the item
          The max character limitation is currently taken from the Yt docs
          https://developers.google.com/youtube/v3/docs/videos#properties
          This may change if another provider is requiring less than 100 characters
        maxLength: 100
        type: string
      visibility:
        description: Visibility of the item
        type: string
    required:
    - storageKey
    - title
    - visibility
    type: object
host: localhost:8080
info:
  contact: {}
  description: An API to store and retrieve videos from a remote hosting service
  title: Video store
  version: "1.0"
paths:
  /playlists:
    post:
      consumes:
      - application/json
      description: Creates a new playlist on the remote video hosting platform
      parameters:
      - description: Required data to create a playlist
        in: body
        name: meta
        required: true
        schema:
          $ref: '#/definitions/video_hosting.ItemMetadata'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Playlist'
        "400":
          description: Required metata are wrong in some ways
        "500":
          description: Internal Server Error
      summary: Creates a new playlist
      tags:
      - playlists
  /playlists/{id}:
    delete:
      description: Delete the playlist by ID if it exists
      parameters:
      - description: Playlist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: No playlist with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete a playlist
      tags:
      - playlists
    get:
      description: Retrieve a playlist by ID
      parameters:
      - description: Playlist ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Playlist'
        "400":
          description: Bad Request
        "404":
          description: No playlist with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get a playlist
      tags:
      - playlists
    put:
      consumes:
      - application/json
      description: Update a playlist by ID if it exists
      parameters:
      - description: Playlist ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated playlist
        in: body
        name: playlist
        required: true
        schema:
          $ref: '#/definitions/video_hosting.Playlist'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Playlist'
        "400":
          description: Bad Request
        "404":
          description: No playlist with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Update a playlist
      tags:
      - playlists
  /playlists/{pid}/videos/{vid}:
    put:
      description: Add an existing playlist to an existing video
      parameters:
      - description: Playlist ID
        in: path
        name: pid
        required: true
        type: integer
      - description: Video ID
        in: path
        name: vid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Either the playlist or video don't exists
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Add a video to the selected playlist
      tags:
      - playlists
  /videos:
    post:
      consumes:
      - application/json
      description: Upload a video from the object storage to the video hosting platform
      parameters:
      - description: Required data to upload a video
        in: body
        name: videometa
        required: true
        schema:
          $ref: '#/definitions/videos_controller.CreateVideoBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Video'
        "400":
          description: Bad Request
        "404":
          description: No video with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Upload a video
      tags:
      - videos
  /videos/{id}:
    delete:
      description: Delete the video by ID if it exists
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: No video with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Delete a video
      tags:
      - videos
    get:
      description: Retrieve a video by ID
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Video'
        "400":
          description: Bad Request
        "404":
          description: No video with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Get a video
      tags:
      - videos
    put:
      consumes:
      - application/json
      description: Update the video by ID if it exists
      parameters:
      - description: Video ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated video
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/video_hosting.Video'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video_hosting.Video'
        "400":
          description: Bad Request
        "404":
          description: No video with this ID
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Update a video
      tags:
      - videos
  /videos/{id}/thumbnail:
    post:
      consumes:
      - application/octet-stream
      description: Set the thumbnail of an existing video on the remote video hosting
        platform
      parameters:
      - description: Video ID
        in: path
        name: key
        required: true
        type: integer
      - description: Thumbnail content
        in: body
        name: thumb
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      summary: Set the thumbnail of a video
      tags:
      - videos
swagger: "2.0"
